### ISSUE TITLE
 aarch64 fails to build on version  1.1.10

### ISSUE THREAD

**Issue by magnetophon** [sadko4u/lsp-plugins#56]
Since the upgrade from 1.1.9 to 1.1.10 aarch64 fails to build on NixOS:
``
In file included from /build/source/include/dsp/dsp.h:11:0,
                 from aarch64.cpp:8:
/build/source/include/dsp/arch/aarch64/features.h:73:45: error: 'HWCAP_ASIMDFHM' was not declared in this scope
     #define HWCAP_AARCH64_ASIMDFHM          HWCAP_ASIMDFHM
                                             ^
/build/source/include/common/types.h:109:41: note: in definition of macro 'IF_ARCH_AARCH64'
     #define IF_ARCH_AARCH64(...)        __VA_ARGS__
                                         ^~~~~~~~~~~
aarch64.cpp:106:11: note: in expansion of macro 'HWCAP_AARCH64_ASIMDFHM'
         { HWCAP_AARCH64_ASIMDFHM, "ASIMDFHM" },
           ^~~~~~~~~~~~~~~~~~~~~~```
``

Any ideas?

**Comment by sadko4u** [comment]
It seems that there is no definition of macro *HWCAP_ASIMDFHM* (which is present on my Arch Linux installation) in your `/usr/include/bits/hwcap.h` file.
Could you please attach some way this file from your system?

**Comment by sadko4u** [comment]
Created branch **github-issue-56** and pushed commit 3e4d4e3522bd6271dd4453c5684fce795a8a5118

Please check whether all builds OK now.

**Comment by sadko4u** [comment]
@magnetophon any news?

**Comment by magnetophon** [comment]
@sadko4u I got a reply from @mmahut  on the NixOS issue saying:
``This should be already included in glibc I think. Hmm.``.

**Comment by sadko4u** [comment]
So, there is no way to test the build with the commit above?

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: eb90df9aeec74079861701c6048c72b705ff361c
Added patch to the **hotfix** branch: 1e3a2189f1ed21270b8e40fca2243c234d825cf8
Assuming the problem being fixed and pending for an upcoming 1.1.11 release.

**Comment by sadko4u** [comment]
Removed **github-issue-56** branch

**Comment by magnetophon** [comment]
Yes there is, no problem, I'm just severely lacking time, sorry!

**Comment by sadko4u** [comment]
Available in the 1.1.11 release!

**Comment by magnetophon** [comment]
great, thanks!
