### PR TITLE
Support cross-compilation

### PR DESCRIPTION
**Pull request by Logarithmus**
Currently cross-compilation is essentially impossible because `src/utils` should be built for host architecture & run on host. Current `Makefile`s are unaware of that, as a result `utils` are being built for target architecture and thus fail to run on host. This PR introduces `HOST_BUILD_ARCH`, `HOST_CXX`, etc. to make cross compilation possible.

The main reason to support cross compilation is to enable packaging for multi-architecture distros like Void Linux.

### CODE REVIEW

**Comment by Logarithmus** [comment]
@sadko4u please take a look at this when you'll have free time.

**Comment by sadko4u** [comment]
This requires some time for understanding all of the changes.

**Comment by sadko4u** [comment]
The idea is clean. Just merged changes. Since 1.2.0 has entirely another build process, such feature should be also introduced for 1.2.0.

**Comment by sadko4u** [comment]
Found a regression while trying to build DSP code on 32-bit platform.
Here's the command-line before the patch:
```
g++ -o /home/sadko/git/lsp-plugins/.test/src/dsp/x86.o -c x86.cpp -fPIC  -m32 -std=c++98 -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -fvisibility=hidden -pipe -Wall  -DLSP_MAIN_VERSION=\"1.1.30\" -DLSP_INSTALL_PREFIX=\"/usr/local\" -O2 -DLSP_TESTING -DLSP_TRACE -g3 -fstack-protector -I"/home/sadko/git/lsp-plugins/include" 
  g++ sse.cpp
```

After the patch:
```
g++ -o /home/sadko/git/lsp-plugins/.native/dsp/sse.o -c sse.cpp -fPIC  -std=c++98 -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -fvisibility=hidden -pipe -Wall  -DLSP_MAIN_VERSION="1.1.30" -DLSP_INSTALL_PREFIX="/usr/local" -mmmx -m3dnow -msse -I"/home/sadko/git/lsp-plugins/include"
In file included from /home/sadko/git/lsp-plugins/include/dsp/dsp.h:25,
                 from sse.cpp:22:
/home/sadko/git/lsp-plugins/include/dsp/arch/x86/sse/mix.h: In function ‘void sse::mix_copy4(float*, const float*, const float*, const float*, const float*, float, float, float, float, size_t)’:
/home/sadko/git/lsp-plugins/include/common/types.h:95:37: error: ‘asm’ operand has impossible constraints
   95 |     #define ARCH_X86_ASM(...)       __asm__ __volatile__ ( __VA_ARGS__ )
      |                                     ^~~~~~~
/home/sadko/git/lsp-plugins/include/dsp/arch/x86/sse/mix.h:860:9: note: in expansion of macro ‘ARCH_X86_ASM’
  860 |         ARCH_X86_ASM
      |         ^~~~~~~~~~~~
```

Several optimization flags for 32-bit x86 architecture are lost and the final code can not be built.
Reverting the changes.

**Comment by sadko4u** [comment]
Reverted commit: 7fa667570cec16c71808f7e322c2b68525c4dfbe

**Comment by Logarithmus** [comment]
> Found a regression while trying to build DSP code on 32-bit platform.
That's unfortunate. Someday I'll revisit this PR & fix it.

**Comment by sadko4u** [comment]
I would like to inform you that currently I'm working on 1.2.0 version which has entirely another build process (since the whole code tree has been split into different repositories).
So you can look at the branch `lsp-plugins-1.2.0` to see the changes. So current build scripts won't live more than 1-2 months.
