### ISSUE TITLE
error: ‘LV2_UI__scaleFactor’ was not declared in this scope; did you mean ‘fUIScaleFactor’?

### ISSUE THREAD

**Issue by darless** [sadko4u/lsp-plugins#328]
Failing to compile with the release 1.2.8

git commit: 
```
commit 15a3733f9d6deccc4c698f08059bc9925a789ef2 (HEAD -> master, tag: 1.2.8, origin/master, origin/HEAD)
Merge: ae45dacb f23eee9e
Author: sadko4u <sadko4u@gmail.com>
Date:   Thu Jul 20 13:52:31 2023 +0300

    Release 1.2.8 
```

Steps:
```
  make clean
  make config FEATURES='lv2'
  make fetch
  make
```

Error seen:
```
  found file: fonts/lsp-logo.ttf
Execution time: 0.02 s
  g++  [lsp-plugin-fw] pluglist_gen
Writing file lsp-plugins/.build/target/lsp-plugin-fw/plugins.php
Writing file lsp-plugins/.build/target/lsp-plugin-fw/plugins.json
  g++  [lsp-plugin-fw] validator
Validating plugin metadata
Overall validation statistics: plugins=162, warnings=0, errors=0

  g++  [lsp-plugin-fw] util/lv2ttl_gen/lv2ttl_gen.cpp
In file included from util/lv2ttl_gen/lv2ttl_gen.cpp:26:
lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/lv2/extensions.h: In constructor ‘lsp::lv2::Extensions::Extensions(const LV2_Feature* const*, const char*, const char*, const char*, LV2UI_Controller, LV2UI_Write_Function)’:
lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/lv2/extensions.h:347:59: error: ‘LV2_UI__scaleFactor’ was not declared in this scope; did you mean ‘fUIScaleFactor’?
  347 |                     uridScaleFactor             = map_uri(LV2_UI__scaleFactor);
      |                                                           ^~~~~~~~~~~~~~~~~~~
      |                                                           fUIScaleFactor
make[3]: *** [Makefile:775: lsp-plugins/.build/host/lsp-plugin-fw/util/lv2ttl_gen/lv2ttl_gen.o] Error 1
make[2]: *** [Makefile:67: all] Error 2
make[1]: *** [Makefile:145: all] Error 2
make: *** [Makefile:68: all] Error 2
```

Environment:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

Kernel 5.15.0-73-generic
```

Compile issue not seen with 1.2.7 following the same procedure.

**Comment by sadko4u** [comment]
Your LV2 development library is out of date.
Do not install `lv2-dev` library while building and all should be OK since LSP Plugins provide fallback source code of the up-to-date LV2 library.
@dvzrv asked to make system libraries prioritized, so here it is.

**Comment by mikelupe** [comment]
It builds fine on Debian 12. Debian 11 though still will be running for some time.

**Comment by sadko4u** [comment]
Just do not include the `lv2-dev` dependency when building the DEB package and all should be OK.

**Comment by dvzrv** [comment]
Alternatively, build in a clean chroot with only the build requirements installed, or use your distribution's lsp-plugins package(s).

**Comment by darless** [comment]
Thank you all. The lv2-dev provided by ubuntu for 20.04 was 1.16.0-1 (4 years old). I downloaded a newer deb 1.18.4-2 and recompiled ok on the new version.
